---
title: "Homework 6"
author: "Stephen Peters-Collaer"
date: "2/23/2022"
output: html_document
---
Click [here](index.html) to return to the main page
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation
```

```{r read in simulated data vector (excluded)}
# quick and dirty, a truncated normal distribution to work on the solution set

#z <- rnorm(n=3000,mean=0.2)
#z <- data.frame(1:3000,z)
#names(z) <- list("ID","myVar")
#z <- z[z$myVar>0,]
#str(z)
#summary(z$myVar)

```

```{r read in own data}
setwd("C:/Users/steph/OneDrive - University of Vermont/Documents/Dissertation_Research/StreamCarbon") #Set working directory where data is located
z1 <- read.csv("hannah_hbef_forest_r.csv")
str(z1)
summary(z1) #The above dataset is a little too complex for the goals here, so I'm going to create a new, simplified dataframe that only has one site 

z <- z1[which(z1$stream == "cushman"),] #create new dataframe only using stream Cushman

z <- z[-3] # remove ID column that has lwd at the front

z$ID <- seq(1:length(z$stream)) #replace the above ID column with a column of integers values

```


```{r plot histogram of data}
p1 <- ggplot(data=z, aes(x=dbh, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1)
```

```{r get maximum likelihood parameters for normal}
normPars <- fitdistr(z$dbh,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute
```

```{r plot normal probability density}
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$dbh),len=length(z$dbh))

 stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$dbh), args = list(mean = meanML, sd = sdML))
 p1 + stat
```

```{r plot exponential probability value}
expoPars <- fitdistr(z$dbh,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$dbh), args = list(rate=rateML))
 p1 + stat + stat2
```

```{r plot uniform probability density}
stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$dbh), args = list(min=min(z$dbh), max=max(z$dbh)))
 p1 + stat + stat2 + stat3
```

```{r plot gamma probability density}
gammaPars <- fitdistr(z$dbh,"gamma", lower = c(0,0))
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]

stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dgamma, colour="brown", n = length(z$dbh), args = list(shape=shapeML, rate=rateML))
 p1 + stat + stat2 + stat3 + stat4
```

```{r plot beta probability density}
pSpecial <- ggplot(data=z, aes(x=dbh/(max(dbh + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$dbh/max(z$dbh + 0.1),start=list(shape1=1,shape2=2),"beta", lower = c(0,0))
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta, colour="orchid", n = length(z$dbh), args = list(shape1=shape1ML,shape2=shape2ML))
pSpecial + statSpecial
```

**Questions 3 and 4**
```{r  simulating dataset based on best fitting distribution}
z2 <- rnorm(n=length(z$ID),mean=normPars$estimate["mean"], sd=normPars$estimate["sd"])
z2 <- data.frame(1:length(z$ID),z2)
colnames(z2) <- c("ID", "myVar")

```

```{r plotting my data and simulated data distributions}
 
#plotting simulated data with a normal distribution
 p2 <- ggplot(data=z2, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 

xval <- seq(0,max(z2$myVar),len=length(z2$myVar))

 stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z2$myVar), args = list(mean = meanML, sd = sdML))
 p2 + stat
 
 #plotting my data with a normal distribution

xval <- seq(0,max(z$dbh),len=length(z$dbh))

 stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$dbh), args = list(mean = meanML, sd = sdML))
 p1 + stat
 
```

