---
title: "Homework4"
author: "Stephen Peters-Collaer"
date: "2/9/2022"
output: html_document
---
Click [here](index.html) to return to the main page


**1.  This is question 1**
```{r}
x <- 1.1 #Define variable
a <- 2.2
b <- 3.3
z <- x^(a^b) #run first equation
print(z) #print result

z <- (x^a)^b # run second equation
print(z)

z <- 3*x^2 +2*x^2 + 1 # run third equation
print(z)

```

**2. This is question 2**
```{r}
v1 <- c(1:8, seq(7,1)) # set first vector
print(v1)

v2 <- rep(1:5, seq(1,5)) # set second vector
print(v2)

v3 <- rep(5:1, seq(1,5)) # set third vector
print(v3)


```

**3.  This is question 3**
```{r}
vector <- runif(2) #create cartesian coordinate
x = vector[1] #isolate X coordinate
y = vector[2] # isolate y coordinate
print(x) #print coordinates
print(y)
r = sqrt(x^2+y^2) #calculate r value for polar coordinates
theta = atan(y/x) # calculate angle value for polar coordinates
print(r) # print results
print(theta)

```

**4.  This is question 4**
```{r}
queue <- c("sheep", "fox", "owl", "ant") # set queue

# a. the serpent arrives and gets in line
queue <- c(queue, "serpent") # add serpent
print(queue)

# b the sheep enters the ark
queue <- queue[-which(queue=="sheep")] #sheep  enters ark
print(queue)

# c the donkey arrives and talks his way to the front of the line
queue <- c("donkey", queue) # donkey cuts line
print(queue)

# d the serpent gets impatient and leaves
queue <- queue[-which(queue=="serpent")]
print(queue)

#e the owl gets bored and leaves
queue <- queue[-which(queue=="owl")]
print(queue)

#f the aphid arrives and the ant invites him to cut in line
queue <- append(queue, "aphid", after = which(queue=="ant")-1)
print(queue)

#g Finally, determine the position of the aphid in the line
which(queue=="aphid")
```

**5.  This is question 5**
```{r}
q5 <- c(1:100) #set q5 to all integers 1-100
print(q5)
q5 <- q5[q5%%2!=0 & q5%%3!=0 & q5%%7!=0] #only select numbers that are not divisible by 2, 3, or 7
print(q5)                    

```

   

